image: "ruby:2.4.1"

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor

build:
  stage: build
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy test
    # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # - eval $(ssh-agent -s)
    # - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # - mkdir -p ~/.ssh
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.name "Roman Rott"
    - git config --global user.email "roman@rrott.com"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
    - middleman build
    - cp source/favicon/* public
    - middleman deploy

rspec:
  stage: test
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy build
  script:
    - bundle exec rspec

# integration:
#   stage: test
#   only:
#     - master
#   before_script:
#     - bundle install --jobs=4 --path vendor --without development deploy build
#   script:
#     - bundle exec rspec

pages:
  stage: deploy
  image: alpine:latest
  environment: staging
  script:
    - ls
  artifacts:
    paths:
      - public
    expire_in: 60 minutes
  only:
    - production

deploy:
  environment: production
  stage: deploy
  only:
    - master
#     - tags
#     - /^production.*$/
  before_script:
    - bundle install --jobs=4 --path vendor --without development test
  script:
    - ls -alh
    # - bundle exec cap production deploy
