image: "ruby:2.3"

cache:
  key: bundle
  paths:
    - vendor

stages:
  - test
  - deploy

before_script:
  - apt-get update -yqqq
  - bundle install -j $(nproc) --path vendor

rubocop:
  stage: test
  script:
  - rubocop

rspec:
  stage: test
  script:
  - bundle exec rspec