image: ruby:2.3
services:
  - ruby

before_script:
  - export LANG="en_US.UTF-8"
  - export LC_ALL="en_US.UTF-8"
  - bundle install

stages:
  - test

spec:
  stage: test
  script:
    - bundle exec rspec
    - rubocop
  tags:
    - ruby