before_script:
  - gem install bundler
  - bundle install

rspec:
  test: "rake spec"
  tags:
    - ruby
  only:
    - branches

# staging:
#   deploy: "cap deploy stating"
#   tags:
#     - capistrano
#     - debian
#   except:
#     - stable

production:
  deploy:
    - cap deploy production
    - cap notify
  tags:
    - capistrano
    - debian
  only:
    - master
    - /^deploy-.*$/