image: ruby:2.3
services:
  - ruby

before_script:
  - bundle install

stages:
  - test
  - deploy

deploy:
  stage: deploy
  script:
  - bundle exec cap production deploy
  only:
    - master
  tags:
    - ruby

spec:
  stage: test
  script:
    - bundle exec rspec
    - rubocop
  only:
    - master
  tags:
    - ruby