image: ruby:2.3
services:
  - ruby
before_script:
  - bundle install

stages:
  - build
  - test

# job1:
#   stage: build
#   script:
#     - bundle exec middleman build
#   only:
#     - master
#   tags:
#     - ruby

job1:
  stage: test
  script:
    - bundle exec rspec
  only:
    - master
  tags:
    - ruby