image: "ruby:2.4.1"

cache:
  paths:
    - vendor

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - master
    - build
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy test
  script:
    # - git branch
    - middleman build
    - cp source/favicon/* build
    # - git checkout build
    - export CI_PUSH_REPO=`echo $CI_BUILD_REPO | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`

    - git checkout -b ci_processing
    - git config --global user.name "GitLab Runner"
    - git config --global user.email "gitlab@rrott.com"
    - git remote set-url --push origin "${CI_PUSH_REPO}"
    - git add .
    - git commit --message "Automated build at $(date +"%Y-%m-%d %H:%M:%S %Z")"
    - git push origin ci_processing:${CI_BUILD_REF_NAME}


rspec:
  stage: test
  only:
    - master
  script:
    - bundle exec rspec
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy build

integration:
  stage: test
  only:
    - master
  script:
    - bundle exec rspec
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy build

deploy:
  environment:
    name: production
  stage: deploy
  only:
    - tags
    - /^production.*$/
  script:
    - bundle exec cap production deploy
  before_script:
    - bundle install  --jobs=4 --path vendor --without development test
