image: ruby:2.3
services:
  - ruby
before_script:
  - bundle install

stages:
  - build
  - test

rubocop:
  stage: build
  script:
    - rubocop
  only:
    - master
  tags:
    - ruby, rrott-digital-ocean

spec:
  stage: test
  script:
    - bundle exec rspec
  only:
    - master
  tags:
    - ruby, rrott-digital-ocean