image: "ruby:2.4.1"

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy test
  script:
    - middleman build
    - cp source/favicon/* build
    - middleman deploy
  artifacts:
    paths:
      - public
    expire_in: 60 minutes

rspec:
  stage: test
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy build
  script:
    - bundle exec rspec

integration:
  stage: test
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development deploy build
  script:
    - bundle exec rspec

pages:
  stage: deploy
  image: alpine:latest
  environment: staging
  script:
    - ls
  artifacts:
    paths:
      - public
    expire_in: 60 minutes
  only:
    - build

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - bundle install --jobs=4 --path vendor --without development test
  script:
    - bundle exec cap production deploy

# deploy:
#   environment: production
#   stage: deploy
#   only:
#     - build
#     - tags
#     - /^production.*$/
#   before_script:
#     - bundle install  --jobs=4 --path vendor --without development test
#   script:
#     - bundle exec cap production deploy
