image: ruby:2.3
services:
  - ruby
before_script:
  - bundle install

stages:
  - build
  - test

job1:
  stage: build
  script:
    - bundle middleman build
    - mv build public
  only:
    - master
  tags:
    - ruby