image: "ruby:2.3.4"

cache:
  paths:
    - vendor

stages:
  - test
  - deploy

before_script:
  - bundle install -j $(nproc) --path vendor

rspec:
  stage: test
  only:
    - master
  script:
    - bundle exec rspec
    - rubocop